### ISSUE TITLE
Fix diagrams

### ISSUE THREAD

**Issue by Jleha** [Jleha/impact#25]
Edit the ER and UML diagrams of a recently modified database

**Comment by YuriiBakhur** [comment]
![Image](https://github.com/Jleha/impact/assets/123874462/44c54432-5e2d-40b9-8295-a3b530b4b66c)

**Comment by Jleha** [comment]
![Image](https://github.com/Jleha/impact/assets/94801705/dde7f23b-6b1f-4051-97ba-8f7d22956678)
